AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for waf rule create and delete

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    CodeUri: function/

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON

Resources:
  DeleteWAFRuleFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: waf_delete.lambda_handler
      Runtime: python3.12
      Role: 'arn:aws:iam::421643133281:role/lambda-execute-waf'
      Architectures:
      - x86_64

  ReCreateWAFRuleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: waf_recreate.lambda_handler
      Runtime: python3.12
      Role: 'arn:aws:iam::421643133281:role/lambda-execute-waf'
      Architectures:
      - x86_64
