version = 0.1

[default]
[default.build.parameters]
debug = true
use_container = false
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
s3_bucket = "aws-sam-and-serverless-framework-349527109315"
region = "ap-northeast-1"

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[prod]
[prod.global.parameters]
stack_name = "aurora-mysql-log-archiver-prod"

[prod.deploy.parameters]
confirm_changeset = true
s3_bucket = "aws-sam-and-serverless-framework-349527109315"
s3_prefix = "aurora-mysql-log-archiver-prod"
region = "ap-northeast-1"
parameter_overrides = "Env=prod"

[stg]
[stg.global.parameters]
stack_name = "aurora-mysql-log-archiver-stg"

[stg.deploy.parameters]
confirm_changeset = true
s3_bucket = "aws-sam-and-serverless-framework-349527109315"
s3_prefix = "aurora-mysql-log-archiver-stg"
region = "ap-northeast-1"
parameter_overrides = "Env=stg"
