AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Aurora MySQL Log Archiver

Parameters:
  BucketName:
    Type: String
    Default: aws-sam-and-serverless-framework-349527109315
  Env:
    Type: String
    AllowedValues:
      - stg
      - prod

Globals:
  Function:
    Runtime: python3.13
    Timeout: 900
    MemorySize: 1024

Resources:
  MySQLLogArchiverFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub aurora-mysql-log-archiver-${Env}
      CodeUri: ../../functions/
      Handler: handler.main
      Environment:
        Variables:
          S3_BUCKET: !If
            - IsProd
            - "archive-aurora-log"
            - "archive-aurora-log-stg"
          PRODUCT: "PRODUCT-A"
          CLUSTERS: !If
            - IsProd
            - "aurora-cluster"
            - "aurora-cluster-stg"
          LOG_TYPES: "audit,error,slowquery"

      Role: arn:aws:iam::349527109315:role/lambda-aurora-mysql-log-archiver
      VpcConfig:
        SubnetIds: !If
          - IsProd
          -
            - subnet-09c9b3b61f15c9320 ## sn-private-1
          -
            - subnet-0998493dab5eefc96 ## sn-private-stg-1

        SecurityGroupIds: !If
          - IsProd
          -
            - sg-038202134d3d37e04 ## default
          -
            - sg-0649c4adf20790d4c ## default
      Events:
        MySQLEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 * * * ? *)
            Name: !Sub aurora-mysql-log-archiver-${Env}

Conditions:
  IsProd: !Equals [!Ref Env, "prod"]
