AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  S3Conversion

Globals:
  Function:
    Timeout: 60
    MemorySize: 128
    CodeUri: func
    Runtime: python3.12
    Architectures:
        - x86_64
    LoggingConfig:
      LogFormat: JSON

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name
  ProjectName:
    Type: String
    Default: event-bucket
    Description: Project name

Outputs:
  S3ConversionFunctionName:
    Description: "Name of the Lambda function"
    Value: !Ref S3ConversionFunction

Resources:  
  #######################################################
  # Lambda Function
  #######################################################
  S3ThumbnailFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: s3-conversion
      Handler: app.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          OUTPUTBUCKET: !Ref TransferBucket
      # Layers:
      #   - !Ref PyminiZipLayer
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref SrcBucket
            # https://docs.aws.amazon.com/ja_jp/AmazonS3/latest/userguide/notification-how-to-event-types-and-destinations.html#supported-notification-event-types
            Events: 
              - s3:ObjectCreated:*

  # PyminiZipLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     LayerName: pyminizip-layer
  #     Description: pyminizip
  #     ContentUri: 'pyminiziplayer/'
  #     CompatibleRuntimes:
  #       - python3.12
  #   Metadata:
  #     BuildMethod: python3.12
  #     BuildProperties:
  #         UseContainer: true

  #######################################################
  # Cloudwatch Logs
  #######################################################
  S3ThumbnailLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${S3ThumbnailFunction}
      RetentionInDays: 7

  #######################################################
  # IAM Role
  #######################################################
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: s3-conversion-lambda-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

      Policies:
        - PolicyName: logs_policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 'arn:aws:logs:ap-northeast-1:*:log-group:*:*'

        - PolicyName: ssm_policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: 'arn:aws:ssm:ap-northeast-1:*:*'

        - PolicyName: s3_policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetBucketAcl"
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:ListBucket"
                Resource: "arn:aws:s3:::*"

        - PolicyName: dynamodb
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:BatchGet*"
                  - "dynamodb:DescribeStream"
                  - "dynamodb:DescribeTable"
                  - "dynamodb:Get*"
                  - "dynamodb:Query"
                  - "dynamodb:Scan"
                  - "dynamodb:BatchWrite*"
                  - "dynamodb:CreateTable"
                  - "dynamodb:Delete*"
                  - "dynamodb:Update*"
                  - "dynamodb:PutItem"
                Resource: "arn:aws:dynamodb:ap-northeast-1:685339645368:table/ThumbnailMetadata"

  #######################################################
  # DynamoDB
  #######################################################
  ThumbnailMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "ThumbnailMetadata"
      AttributeDefinitions:
        - AttributeName: "image_id"
          AttributeType: "S"
        - AttributeName: "original_filename"
          AttributeType: "S"
        - AttributeName: "created_at"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "image_id" # パーティションキー（HASH）
          KeyType: "HASH"
        - AttributeName: "original_filename" # ソートキー（RANGE）
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "3"
        WriteCapacityUnits: "3"
